services:
  mediafusion:
    image: mhdzumair/mediafusion
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 20m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      mediafusion-network: {}

  mongodb:
  image: mongo:6.0
  environment:
    MONGO_INITDB_ROOT_USERNAME: mediafusion
    MONGO_INITDB_ROOT_PASSWORD: mfpass123
    MONGO_INITDB_DATABASE: mediafusion
  volumes:
    - mongo-data:/data/db
  ports:
    - "27017:27017"
  restart: unless-stopped
  networks:
    mediafusion-network: {}

redis:
  image: redis:7.2
  command: redis-server --requirepass redispw123 --appendonly yes --save 60 1
  environment:
    REDIS_PASSWORD: redispw123
  ports:
    - "6379:6379"
  volumes:
    - redis-data:/data
  restart: unless-stopped
  networks:
    mediafusion-network: {}

  dramatiq-worker:
    image: mhdzumair/mediafusion
    command: ["dramatiq", "api.task", "-p", "1", "-t", "4"]
    env_file: .env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      mediafusion-network: {}

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ:-UTC}
    ports:
      - "9696:9696"
    volumes:
      - prowlarr-config:/config
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      mediafusion-network: {}

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - "8191:8191"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8191/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      mediafusion-network: {}

  browserless:
    image: ghcr.io/browserless/chromium
    ports:
      - "3001:3001"
    environment:
      - TIMEOUT=-1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      mediafusion-network: {}

volumes:
  mongo-data:
    driver: local
  prowlarr-config:
    driver: local
  redis-data:
    driver: local

networks:
  mediafusion-network:
    driver: bridge
